package com.example.runnerapp.other

object Constants {

const val RUNNING_DATABASE_NAME="running_db"
const val ACTION_START_OR_RESUME_SERVICE="ACTION_START_OR_RESUME_SERVICE"
const val ACTION_STOP_SERVICE="ACTION_STOP_SERVICE"
const val ACTION_PAUSE_SERVICE="ACTION_PAUSE_SERVICE"
}